### PR TITLE
Update images & SpecialEvents transition

### PR DESCRIPTION
**Pull request by lemonadedw**

### CODE REVIEW

**Comment by lemonadedw** [comment]
@lihe07 why failed

**Comment by lihe07** [comment]
> @lihe07 why failed

后缀名大小写问题
原始：`'../../assets/images/HomePage/Spring.jpg?webp'`
应该是：`'../../assets/images/HomePage/Spring.JPG?webp'`

也可以直接修改文件后缀名

**Comment by lemonadedw** [comment]
oh ok

**Comment by lemonadedw** [comment]
ok @lihe07

**Review by lihe07 — APPROVED** [review]
OK

**Pull request merged**
