### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by lemonadedw**

### CODE REVIEW

**Comment by lemonadedw** [comment]
我的joinStudent怎么没了？？？

**Comment by lemonadedw** [comment]
ok

**Comment by lemonadedw** [comment]
@lihe07

**Review by lihe07 — APPROVED** [review]

**Comment by lihe07** [comment]
> 我的joinStudent怎么没了？？？

Some bugs of git and fs. Cuz I once triggered `yarn format` and interrupted it, generating some corrupted chunks. 
Hopefully it will gone after merging.

**Comment by lemonadedw** [comment]
np 我加回来了
________________________________

**Pull request merged**
