### PR TITLE
Fix Club Data & Update Curriculum Info & Fix EducationTeaching

### PR DESCRIPTION
**Pull request by lemonadedw**
@mike-wu2006

### CODE REVIEW

**Comment by lihe07** [comment]
Seems caused by `vite-imagetools`
Try manually add `imagetools-core` into dependencies

**Comment by lemonadedw** [comment]
ok

**Comment by lemonadedw** [comment]
mufeng的page 样式上的小问题还挺多的 晚上我和他说声吧

**Review by lihe07 — APPROVED** [review]
✅

**Pull request merged**
